### ISSUE TITLE
Emitter/Receiver Packet Acknowledgements

### ISSUE THREAD

**Issue by METACEO** [pm2-hive/pm2-intercom#2]
It'd be amazing if this feature could be worked in! Referencing the draft examples over at [Unitech's PM2 issue #1826](https://github.com/Unitech/pm2/issues/1826), I edited them below to represent something along the lines of [socket.io's acknowledgement](http://socket.io/docs/#sending-and-getting-data-(acknowledgements)) implementation:

Emitter app:
```javascript
process.send({
  topic:'intercom',
  target:'receiver_app_a',
  data:{
    some:"data"
  },
  ack:function(result,arg2,arg3){
    /*
    * Will later get the below from the receiver:
    *  result === 'ok!'
    *  arg2   === {some:"data"}
    *  arg3   === {abc:123}
    */
  }
});
```
Receiver app:
```javascript
process.on('message',function(packet){
  if(packet.topic == 'intercom'){
    // Access to my data
    console.log(packet.data);
    
    packet.ack('ok!',packet.data,{abc:123});
    
  }
});
```

I have been hacking together acknowledgement features using [node-ipc](https://github.com/RIAEvangelist/node-ipc) but I then found `pm2-intercom` and thought this feature would be quite appropriate and useful here. What I have in mind is one application targeting another with a data payload and expecting a response back. My hacked approach with `node-ipc` sent a request (all via UNIX sockets) to another application with data that included a unique identifier. That targeted application would receive the request, process it and send a request that (with that unique identifier) would be seen by the original application as a response. The original application would process the response by calling the function from its original request with the results from that response.

I don't know yet how `socket.io` implements its acknowledgements but I do know it works both ways (from server to client and from client to server) and that it's a tremendous help. Hopefully the examples I posted above show better than me telling. Amazing module nonetheless!..

**Comment by Unitech** [comment]
Thanks for your interest!

> My hacked approach with node-ipc sent a request (all via UNIX sockets) to another application with data that included a unique identifier. That targeted application would receive the request, process it and send a request that (with that unique identifier) would be seen by the original application as a response.

This is the good approach when you play with [asynchronous message](https://github.com/tj/axon/blob/master/lib/sockets/req.js#L64)

PR welcome :)

**Comment by G3E9** [comment]
Awesome!.. wrong reasons took me to `axon` before but thank you for the new direction now (and to the precise line!) PM2 remains my go-to for process management and it'll be what I continue to offer and suggest for others... keep up the work!

**Comment by thelonglqd** [comment]
I cannot install pm2-intercom with pm2 1.0.1 version, Is it disable ?

**Comment by METACEO** [comment]
@thelonglqd I just verified that it is *not* disabled and that it *is* working, do the following.

```
$ npm install -g pm2
...
$ pm2 install pm2-intercom
```

Create the file `on.js` with this from the README.md

```javascript
process.on('message', function(packet) {
  if (packet.topic == 'cmd:topic') {
    console.log('Received packet', packet.data);
  }
});
```

Run `pm2 start on.js` then create the file `send.js` with this from the README.md

```javascript
process.send({
  topic : 'cmd:topic',
  data  : {
    some : 'data'
  }
});
```

Run `pm2 start send.js` and find the log file of the `on.js`, you should see this here:

```
Received packet { some: 'data' }
```

If you cannot do this or you cannot find the above in your log file, then please open a new issue and reference me (or reference this issue) in it.

**Comment by thelonglqd** [comment]
I did exactly what you said, but the error still appear. Does pm2 has any verbose logging for `pm2 install <module>` command? With `unknow module`, I can not trace the problem.
