### ISSUE TITLE
pm2-intercom-0 [Error: Process with ID ]

### ISSUE THREAD

**Issue by nazarhussain** [pm2-hive/pm2-intercom#3]
I had created a file `on.js` with content
```
process.on('message', function(packet) {
  if (packet.topic == 'cmd:topic') {
    console.log('Received packet', packet.data);
  }
});
```
and a file `send.js` with the file
```
process.send({
  topic : 'cmd:topic',
  data  : {
    some : 'data'
  }
});
```

When I run `pm2 start send.js` it shows following error in logs. 
```
PM2 Starting execution sequence in -fork mode- for app name:send id:11
PM2 App name:send id:11 online
PM2 Process with ID
PM2 Process with ID
pm2-intercom-0 [Error: Process with ID ]
pm2-intercom-0 [Error: Process with ID ]
PM2 App [send] with id [11] and pid [24815], exited with code [0] via signal [SIGINT]
```
And this same error start occurring indefinite times. 

@METACEO As per your instructions on https://github.com/pm2-hive/pm2-intercom/issues/2#issuecomment-184869915 I am referencing you here.

**Comment by METACEO** [comment]
@nazarhussain @thelonglqd I've just posted a Gist [here](https://gist.github.com/METACEO/250db318d26b18aea1e2c55fedbab383) that will provide you a working intercom example. It's CentOS specific but it should still be somewhat applicable to whatever system you're using.

Is your `on.js` logging though? If your `send.js` finishes execution, then PM2 will restart it. Can you try what you've been doing and after 5-10 seconds post here the `pm2 list` output?

**Comment by nazarhussain** [comment]
@METACEO I wonder why but `pm2 delete all` and then `pm2 start on.js` and `pm2 start send.js` did the trick.
